version: '3.8'
services:
  app:
    image: 'servicos:latest'
    build:
      context: .
    container_name: servicos
    depends_on:
      - postgres
    ports:
      - 8080:8080

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: teste@teste.com
      PGADMIN_DEFAULT_PASSWORD: teste
    ports:
      - 16543:80
    volumes:
      - ./servers.json:/pgadmin4/servers.json

volumes:
  postgres-db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./postgresql
